### PR TITLE
Hubble + Travis = <3

### PR DESCRIPTION
**Pull request by filmaj**

### CODE REVIEW

**Comment by filmaj** [comment]
woops my bad. i was supposed to send this to my own repo for testing first! my bad. closing.

**Comment by pluehne** [comment]
No worries. You may just reopen this once you’re done persuading Travis to run without errors 😃.

**Comment by filmaj** [comment]
OK I think this is ready to go. Nothing but the basic scaffolding for the Python bits, but once we figure out tests for that, shouldn't be too hard to add commands to the travis file to install dependencies and run tests.

It looks like Travis is already executing here... so I'm not sure if someone from the project already went and a) logged into Travis with their GitHub account and b) enabled Autodesk/hubble repo to run against Travis - but it looks like it. So yay! Now we get pretty green check marks on the PR list page, or angry red checkmarks if tests fail 😄

**Comment by filmaj** [comment]
Oh, I'll also add a Travis badge to the readme.

**Comment by pluehne** [comment]
I was a bit overzealous and turned on Travis as soon as you opened this pull request 😃. And apparently, the first CI build succeeded!

**Comment by filmaj** [comment]
Great, it's been fun working with y'all so far - hope to continue that! I am looking forward to growing and contributing to the Hubble project 😄

**Comment by pluehne** [comment]
That sounds great, looking forward to it!

**Pull request merged**
